# Generated by Django 3.2 on 2022-02-23 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='dept_name')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=30, verbose_name='role')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('emp_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=30, verbose_name='employee_name')),
                ('date_of_birth', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('bank_ac_no', models.BigIntegerField()),
                ('pf_no', models.CharField(max_length=40, null=True)),
                ('dept', models.OneToOneField(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='employee.department')),
                ('designation', models.OneToOneField(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='employee.designation')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fixed_anual_ctc', models.FloatField()),
                ('balance_leaves', models.IntegerField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
            ],
        ),
    ]
