# Generated by Django 3.2 on 2022-02-24 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='fixed_anual_ctc',
            new_name='fixed_annual_ctc',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='balance_leaves',
        ),
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='employee.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='employee.designation'),
        ),
        migrations.CreateModel(
            name='EmployeeLeaves',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('working_days', models.IntegerField(default=22)),
                ('total_leaves', models.IntegerField(default=22)),
                ('balance_leaves', models.IntegerField()),
                ('emp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
