# Generated by Django 3.2 on 2022-02-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20220224_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bank_ac_no',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pf_no',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
