# Generated by Django 3.2 on 2022-02-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20220224_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='reimbursement_date',
            field=models.DateField(default='2022-02-25'),
            preserve_default=False,
        ),
    ]
